### ISSUE TITLE
invalid byte sequence

### ISSUE THREAD

**Issue by nathanhaigh** [wurmlab/sequenceserver#310] opened 2016-10-03 20:41 UTC
I came across this issue and have a possible solution. I'm posting here as I don't know if the solution is the best or most appropriate.

I'm configuring Apache/Passenger on Ubuntu 16.04 and got this error in the Apache log (`/var/log/apache2/error.log`):

```
occurred while starting up the preloader.
  Error ID: 491f5249
  Error details saved to: /tmp/passenger-error-PbYTrs.html
  Message from application: invalid byte sequence in US-ASCII (ArgumentError)
  /var/www/sequenceserver/lib/sequenceserver/database.rb:117:in `split'
  /var/www/sequenceserver/lib/sequenceserver/database.rb:117:in `block (2 levels) in scan_databases_dir'
  /var/www/sequenceserver/lib/sequenceserver/database.rb:116:in `each_line'
  /var/www/sequenceserver/lib/sequenceserver/database.rb:116:in `block in scan_databases_dir'
  /usr/lib/ruby/2.3.0/open3.rb:205:in `popen_run'
  /usr/lib/ruby/2.3.0/open3.rb:95:in `popen3'
  /var/www/sequenceserver/lib/sequenceserver/database.rb:112:in `scan_databases_dir'
  /var/www/sequenceserver/lib/sequenceserver.rb:140:in `init_database'
  /var/www/sequenceserver/lib/sequenceserver.rb:45:in `init'
  config.ru:4:in `block in <main>'
  /var/lib/gems/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
  /var/lib/gems/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
```

I fixed this by adding the following to the bottom of my `Gemfile` folloiwng information from http://stackoverflow.com/a/17031697/1413849:

```
if RUBY_VERSION =~ /2.3/ # assuming you're running Ruby ~2.3
  Encoding.default_external = Encoding::UTF_8
  Encoding.default_internal = Encoding::UTF_8
end
```

My sequenceserver site now loads correctly.

FYI, my locale is:

```
$ locale
LANG=en_AU.UTF-8
LANGUAGE=en_AU:en
LC_CTYPE="en_AU.UTF-8"
LC_NUMERIC="en_AU.UTF-8"
LC_TIME="en_AU.UTF-8"
LC_COLLATE="en_AU.UTF-8"
LC_MONETARY="en_AU.UTF-8"
LC_MESSAGES="en_AU.UTF-8"
LC_PAPER="en_AU.UTF-8"
LC_NAME="en_AU.UTF-8"
LC_ADDRESS="en_AU.UTF-8"
LC_TELEPHONE="en_AU.UTF-8"
LC_MEASUREMENT="en_AU.UTF-8"
LC_IDENTIFICATION="en_AU.UTF-8"
LC_ALL=
```

**Comment by yeban** [comment] 2017-01-06 09:52
Dear @nathanhaigh, thanks for reporting the problem and sharing a solution. The issue is the same as discussed at #188. I am thus closing it.

**Closed by yeban** 2017-01-06 09:52 UTC
