### ISSUE TITLE
download FASTA fails

### ISSUE THREAD

**Issue by enuggetry** [wurmlab/sequenceserver#475] opened 2020-07-03 06:40 UTC
Version 2.0.rc5
I'm getting this error when I click any of the FASTA download links.  This happened on rc4 too.
How can I resolve this?
{
   "message":"SequenceServer::CommandFailed",
   "title":"SequenceServer::CommandFailed",
   "more_info":"/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequenceserver-2.0.0.rc5/lib/sequenceserver/sys.rb:83:in `sys'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequenceserver-2.0.0.rc5/lib/sequenceserver/sequence.rb:203:in `run'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequenceserver-2.0.0.rc5/lib/sequenceserver/sequence.rb:182:in `initialize'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequenceserver-2.0.0.rc5/lib/sequenceserver/routes.rb:130:in `new'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequenceserver-2.0.0.rc5/lib/sequenceserver/routes.rb:130:in `block in '\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `call'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `block in compile!'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (3 levels) in route!'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1006:in `route_eval'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (2 levels) in route!'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1035:in `block in process_route'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `catch'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `process_route'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:985:in `block in route!'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `each'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `route!'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1098:in `block in dispatch!'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1095:in `dispatch!'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `block in call!'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `call!'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:908:in `call'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/deflater.rb:44:in `call'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/head.rb:12:in `call'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:194:in `call'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1951:in `call'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1503:in `block in call'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1730:in `synchronize'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1503:in `call'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequenceserver-2.0.0.rc5/lib/sequenceserver.rb:114:in `call'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/handler/webrick.rb:95:in `service'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/2.5.0/webrick/httpserver.rb:140:in `service'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/2.5.0/webrick/httpserver.rb:96:in `run'\n/home/ericiam/.rbenv/versions/2.5.0/lib/ruby/2.5.0/webrick/server.rb:307:in `block in start_thread'"
}

**Comment by yeban** [comment] 2020-07-03 14:06
Not sure, as I cannot reproduce it. I will need a few days to push a version with some diagnostic output that can help trace the issue. In the meantime, you can try running SequenceServer in development mode. This will cause the command that is run to be output to the console/log file. You can then try to run the command directly to see if that works.

To run SequenceServer in development mode either run `sequenceserver -D`, or if you are using Apache+Passenger, add `ENV['RACK_ENV'] = 'development'` to the top of `config.ru` (even before `require 'sequenceserver'`).

**Comment by enuggetry** [comment] 2020-07-03 20:28
I wonder if it has to do with the fact that I run it as a port proxy from apache2.

**Comment by enuggetry** [comment] 2020-07-04 02:45
I tried it on an unproxied server and it had the same problem.

**Comment by enuggetry** [comment] 2020-07-04 03:22
I think the issue may lay somewhere here:
My sequence ids look like this >gnl|MorexV2|chr1H
So that when the results are rendered, the user can identify the database and links.rb can identify the database

Download FASTA calls (where it only passes the chromosome id): 
`blastdbcmd -outfmt '%g  %i      %a      %t      %s' -db '/data/blast_db/db2/MorexV2/MorexV2' -entry 'chr1H'`

which causes this error: 
```
Error: [blastdbcmd] Entry not found: CHR1H
Error: [blastdbcmd] Entry or entries not found in BLAST database
```

I think it should be:
`blastdbcmd -outfmt '%g  %i      %a      %t      %s' -db '/data/blast_db/db2/MorexV2/MorexV2' -entry 'gnl|MorexV2|chr1H'`

**Comment by yeban** [comment] 2020-07-14 17:38
Hi. Thanks for investigating the issue and sharing the details. I can reproduce the issue now. I will try to fix it next week - been a bit tied down by other commitments. Thanks for being patient.

**Comment by yeban** [comment] 2020-07-28 10:08
So a quick look suggests this is a bug BLAST in the new database format. The command `blastdbcmd -outfmt '%g %i %a %t %s' -db '/data/blast_db/db2/MorexV2/MorexV2' -entry 'chr1H'` works fine with the older V4 databases. I will first report the issue to NCBI and see what they say.

**Comment by yeban** [comment] 2020-08-10 15:36
Quick update: NCBI's response suggests that the behaviour with V5 databases is intended and not a bug. So I guess we are going to have to work with that. I am going to need some time to push a fix: Using the whole id for sequence retrieval will require encoding the `|` special character in it. I am currently unsure if doing so can have unwanted side-effects in other parts of the code.

**Comment by yeban** [comment] 2020-08-13 13:22
Okay, I have pushed a fix (`gem install --pre sequenceserver`). Let me know if you run into any other problems. Thanks for being patient and for supporting with a stream thumbs up :)

**Closed by yeban** 2020-08-13 13:22 UTC

**Comment by enuggetry** [comment] 2020-08-13 23:05
Thank you! will do.

**Comment by enuggetry** [comment] 2020-08-25 11:42
seems to work just fine.  thank you.

**Comment by yeban** [comment] 2020-08-26 13:09
Thanks for confirming!
