### ISSUE TITLE
Use params from last search

### ISSUE THREAD

**Issue by yeban** [wurmlab/sequenceserver#16] opened 2011-04-17 14:10 UTC
Allow a user to save searches.

The idea is that Biologists often want to run the same blast over different sequences. So, it would be helpful to provide a mechanism to save blast method, databases used, and probably advanced options.

A simple way to achieve this is to marshal the search parameters and store it as cookies (4096 bytes ought to be enough). When user comes back, read the cookies, and give him/her an option to restore previous search parameters.

Another way is to use a database to store to store searches on the server side. We can then store sequences too, but I am not sure if that is very practical. Sqlite can be  used for its simplicity; bigger databases would make it difficult to deploy. Being able to choose different databases depending on the deployment size could be a good feature too.

Thanks to Jan for this suggestion.

**Comment by yeban** [comment] 2015-03-18 13:49
If we implement this, it would be a simple "Use parameters from last search" link somewhere in the search form and nothing more.

**Comment by yeban** [comment] 2015-09-16 05:31
Browser now automatically saves and suggests 'advanced params' from previous searches (side-effect of #181).

**Comment by lukaszsobala** [comment] 2024-02-05 11:25
I think this is a bug (at least in version 2.0.0). I have a public BLAST server here: https://lukprot.hirszfeld.pl

It seems that the default parameters from the .sequenceserver.conf file are not loaded every time, but instead, the advanced parameters of the last search made using the server are loaded. Obviously, I want people who visit the server to see the defaults set in the file.

I cannot at the moment test Sequenceserver 2.2.0 - maybe this was fixed in the meantime? Please let me know.

**Comment by lukaszsobala** [comment] 2024-02-08 13:30
Copying my edits here into a new comment:

1) using private tabs in 2 different browsers, I could not reproduce it for a while. I don't know how this it might have happened then. I was investigating further.
2) I did reproduce this using different private tabs. The parameters I used in one of the searches remain there as "defaults". Only when I restart sequenceserver, the "normal" defaults reappear. I will try to isolate the error.

**Comment by yeban** [comment] 2024-02-08 20:28
Hi @lukaszsobala @yannickwurm The issue you mentioned is likely fixed since 2.1.0. I think by this commit: e4787a6d02c85c3fcd257695072e37a3306dc64b. Basically the values are read from config file and stored in memory but the in-memory was somehow getting modified.

**Comment by lukaszsobala** [comment] 2024-02-09 13:30
Hi @yeban, thanks for clarifying. If you could offer support on how to get databases to the `/db` directory in the docker volume I can test this.
The instructions here are unclear: 
https://hub.docker.com/r/wurmlab/sequenceserver

I am doing it this way:
`docker run -it -p 4568:4568 wurmlab/sequenceserver` (not sure why you have -rm there in the example as it would remove the image immediately after stopping?)

It always complains about `/db` being empty and exits.

Or, much better, how I can mount the /db directory from the docker image to a directory I want that is outside docker.

**Comment by lukaszsobala** [comment] 2024-02-09 14:56
@yeban @yannickwurm it seems that the issue was indeed fixed in the commit https://github.com/wurmlab/sequenceserver/commit/e4787a6d02c85c3fcd257695072e37a3306dc64b.

I will try to migrate to the docker container but I think it needs a bit more documentation, for example it is not clear how to "properly" edit the `.sequenceserver.conf` file etc. I also have a problem with the BLAST search page not showing up when clicking on the BLASTP button (even with the "Open in the new page" option set) but this seems to be related to our network configuration, as it works on local docker. If you have any suggestions, please write. This can be closed.

**Closed** 2024-02-09 15:27 UTC
Labels: feature

**Comment by yeban** [comment] 2024-02-09 20:33
Hi @lukaszsobala As you have figured out already how to mount your local database folder to `/db` in container, you can take the same approach for the config file. In the docker image, the config file is located at `/root/.sequenceserver.conf`. 

So adding something like `--mount src=/path/to/config_file,target=/root/.sequenceserver.conf,type=bind` to your `docker run` command should do the trick (or using the `-v` syntax that I am more familiar with: `-v /path/to/config_file:/root/.sequenceserver.conf`).

And make sure you have `:database_dir: "/db"` line in your config file.
